using System.IO.Compression;
using System.Text;
using Moq;
using NoviVovi.Application.Common.Abstractions;
using NoviVovi.Application.Common.Exceptions;
using NoviVovi.Application.Novels.Abstractions;
using NoviVovi.Domain.Characters;
using NoviVovi.Domain.Common;
using NoviVovi.Domain.Dialogue;
using NoviVovi.Domain.Labels;
using NoviVovi.Domain.Novels;
using NoviVovi.Domain.Steps;
using NoviVovi.Infrastructure.Exporters.RenPy.Core.Characters.Mappers;
using NoviVovi.Infrastructure.Exporters.RenPy.Core.Labels.Mappers;
using NoviVovi.Infrastructure.Exporters.RenPy.Core.Novels.Mappers;
using NoviVovi.Infrastructure.Exporters.RenPy.Core.Scene.Mappers;
using NoviVovi.Infrastructure.Exporters.RenPy.Core.Statements.Mappers;
using NoviVovi.Infrastructure.Exporters.RenPy.Services;
using NoviVovi.Infrastructure.Exporters.RenPy.Services.Archive;
using NoviVovi.Infrastructure.Exporters.RenPy.Services.Images;
using NoviVovi.Infrastructure.Exporters.RenPy.Services.Resources;
using NoviVovi.Infrastructure.Exporters.RenPy.Services.Script;
using NoviVovi.Infrastructure.Exporters.RenPy.Services.Utilities;
using Xunit;

namespace NoviVovi.Infrastructure.Tests.Exporters.RenPy;

/// <summary>
/// Integration tests for RenPyExporter - the main orchestrator.
/// </summary>
public class RenPyExporterTests
{
    private readonly Mock<INovelRepository> _mockRepository;
    private readonly Mock<IStorageService> _mockStorage;
    private readonly Mock<IEmbeddedResourceLoader> _mockResourceLoader;
    private readonly RenPyExporter _exporter;

    public RenPyExporterTests()
    {
        _mockRepository = new Mock<INovelRepository>();
        _mockStorage = new Mock<IStorageService>();
        _mockResourceLoader = new Mock<IEmbeddedResourceLoader>();

        // Setup real services (no mocks for business logic)
        var identifierGenerator = new RenPyIdentifierGenerator();
        var transformMapper = new TransformToRenPyMapper();
        var characterMapper = new CharacterToRenPyMapper(identifierGenerator);
        var stepMapper = new StepToRenPyMapper(identifierGenerator, transformMapper);
        var labelMapper = new LabelToRenPyMapper(identifierGenerator, stepMapper);
        var novelMapper = new NovelToRenPyMapper(identifierGenerator, characterMapper, labelMapper);
        
        var statementRenderer = new RenPyStatementRenderer();
        var scriptGenerator = new RenPyScriptGenerator(_mockResourceLoader.Object, statementRenderer);
        
        var imageCollector = new NovelImageCollector();
        var imageExporter = new RenPyImageExporter(_mockStorage.Object);
        
        var archiveBuilder = new RenPyArchiveBuilder(_mockResourceLoader.Object);

        _exporter = new RenPyExporter(
            _mockRepository.Object,
            novelMapper,
            scriptGenerator,
            imageCollector,
            imageExporter,
            archiveBuilder
        );

        // Setup template mock
        var templateContent = @"## Generated by NoviVovi - {{ title }}

## Character Definitions
{{~ for character in characters ~}}
define {{ character.variable_name }} = Character(""{{ character.display_name }}"", color=""{{ character.color }}"")
{{~ end ~}}

## Game Start
label start:
{{~ for label in labels ~}}
{{~ if label.identifier == start_label_id ~}}
{{~ for statement in label.statements ~}}
{{ render_statement statement }}
{{~ end ~}}
{{~ end ~}}
{{~ end ~}}
    return

## Labels
{{~ for label in labels ~}}
{{~ if label.identifier != start_label_id ~}}

label {{ label.identifier }}:
{{~ for statement in label.statements ~}}
{{ render_statement statement }}
{{~ end ~}}
    return
{{~ end ~}}
{{~ end ~}}";

        _mockResourceLoader
            .Setup(x => x.LoadTextResourceAsync(
                "NoviVovi.Infrastructure.Exporters.RenPy.Templates.script.rpy.sbn",
                It.IsAny<CancellationToken>()))
            .ReturnsAsync(templateContent);

        _mockResourceLoader
            .Setup(x => x.LoadStreamResourceAsync(
                "NoviVovi.Infrastructure.Exporters.RenPy.Resources.BaseProject.zip",
                It.IsAny<CancellationToken>()))
            .ReturnsAsync((Stream?)null);
    }

    [Fact]
    public async Task ExportToRenPyAsync_MinimalNovel_ReturnsValidZip()
    {
        // Arrange
        var novel = Novel.Create("Test Novel", "start");
        var character = Character.Create("Narrator", Color.FromHex("#ffffff"), null);
        novel.AddCharacter(character);
        
        var replica = Replica.Create(character, "Hello World");
        var replicaStep = ShowReplicaStep.Create(replica);
        novel.StartLabel.AddStep(replicaStep);

        _mockRepository
            .Setup(x => x.GetByIdAsync(novel.Id, It.IsAny<CancellationToken>()))
            .ReturnsAsync(novel);

        // Act
        var zipBytes = await _exporter.ExportToRenPyAsync(novel.Id, CancellationToken.None);

        // Assert
        Assert.NotNull(zipBytes);
        Assert.NotEmpty(zipBytes);

        // Verify ZIP structure
        using var memoryStream = new MemoryStream(zipBytes);
        using var archive = new ZipArchive(memoryStream, ZipArchiveMode.Read);

        var scriptEntry = archive.GetEntry("game/script.rpy");
        Assert.NotNull(scriptEntry);

        using var scriptStream = scriptEntry.Open();
        using var reader = new StreamReader(scriptStream, Encoding.UTF8);
        var scriptContent = await reader.ReadToEndAsync();

        Assert.Contains("Test Novel", scriptContent);
        Assert.Contains("define char_", scriptContent);
        Assert.Contains("Hello World", scriptContent);
    }

    [Fact]
    public async Task ExportToRenPyAsync_NonExistentNovel_ThrowsNotFoundException()
    {
        // Arrange
        var novelId = Guid.NewGuid();
        _mockRepository
            .Setup(x => x.GetByIdAsync(novelId, It.IsAny<CancellationToken>()))
            .ReturnsAsync((Novel?)null);

        // Act & Assert
        await Assert.ThrowsAsync<NotFoundException>(
            () => _exporter.ExportToRenPyAsync(novelId, CancellationToken.None)
        );
    }

    [Fact]
    public async Task ExportToRenPyAsync_NovelWithMultipleCharacters_IncludesAllCharacters()
    {
        // Arrange
        var novel = Novel.Create("Multi Character Novel", "start");
        
        var char1 = Character.Create("Alice", Color.FromHex("#ff0000"), null);
        var char2 = Character.Create("Bob", Color.FromHex("#00ff00"), null);
        novel.AddCharacter(char1);
        novel.AddCharacter(char2);
        
        var replica1 = Replica.Create(char1, "Hello from Alice");
        var replica2 = Replica.Create(char2, "Hello from Bob");
        var replicaStep1 = ShowReplicaStep.Create(replica1);
        var replicaStep2 = ShowReplicaStep.Create(replica2);
        novel.StartLabel.AddStep(replicaStep1);
        novel.StartLabel.AddStep(replicaStep2);

        _mockRepository
            .Setup(x => x.GetByIdAsync(novel.Id, It.IsAny<CancellationToken>()))
            .ReturnsAsync(novel);

        // Act
        var zipBytes = await _exporter.ExportToRenPyAsync(novel.Id, CancellationToken.None);

        // Assert
        using var memoryStream = new MemoryStream(zipBytes);
        using var archive = new ZipArchive(memoryStream, ZipArchiveMode.Read);
        var scriptEntry = archive.GetEntry("game/script.rpy");
        
        using var scriptStream = scriptEntry!.Open();
        using var reader = new StreamReader(scriptStream, Encoding.UTF8);
        var scriptContent = await reader.ReadToEndAsync();

        Assert.Contains("Alice", scriptContent);
        Assert.Contains("Bob", scriptContent);
        Assert.Contains("Hello from Alice", scriptContent);
        Assert.Contains("Hello from Bob", scriptContent);
    }

    [Fact]
    public async Task ExportToRenPyAsync_NovelWithMultipleLabels_IncludesAllLabels()
    {
        // Arrange
        var novel = Novel.Create("Multi Label Novel", "intro");
        var character = Character.Create("Guide", Color.FromHex("#ffcc00"), null);
        novel.AddCharacter(character);
        
        var introReplica = Replica.Create(character, "Welcome!");
        var introStep = ShowReplicaStep.Create(introReplica);
        novel.StartLabel.AddStep(introStep);
        
        var chapter1 = Label.Create("chapter1", novel.Id);
        var ch1Replica = Replica.Create(character, "Chapter 1");
        var ch1Step = ShowReplicaStep.Create(ch1Replica);
        chapter1.AddStep(ch1Step);
        novel.AddLabel(chapter1);

        _mockRepository
            .Setup(x => x.GetByIdAsync(novel.Id, It.IsAny<CancellationToken>()))
            .ReturnsAsync(novel);

        // Act
        var zipBytes = await _exporter.ExportToRenPyAsync(novel.Id, CancellationToken.None);

        // Assert
        using var memoryStream = new MemoryStream(zipBytes);
        using var archive = new ZipArchive(memoryStream, ZipArchiveMode.Read);
        var scriptEntry = archive.GetEntry("game/script.rpy");
        
        using var scriptStream = scriptEntry!.Open();
        using var reader = new StreamReader(scriptStream, Encoding.UTF8);
        var scriptContent = await reader.ReadToEndAsync();

        Assert.Contains("label start:", scriptContent); // start label is always "start"
        Assert.Contains("label label_", scriptContent); // chapter1 gets GUID-based name
        Assert.Contains("Welcome!", scriptContent);
        Assert.Contains("Chapter 1", scriptContent);
    }

    [Fact]
    public async Task ExportToRenPyAsync_CyrillicNovel_PreservesEncoding()
    {
        // Arrange
        var novel = Novel.Create("Тестовая Новелла", "начало");
        var character = Character.Create("Алиса", Color.FromHex("#ff69b4"), null);
        novel.AddCharacter(character);
        
        var replica = Replica.Create(character, "Привет, мир!");
        var replicaStep = ShowReplicaStep.Create(replica);
        novel.StartLabel.AddStep(replicaStep);

        _mockRepository
            .Setup(x => x.GetByIdAsync(novel.Id, It.IsAny<CancellationToken>()))
            .ReturnsAsync(novel);

        // Act
        var zipBytes = await _exporter.ExportToRenPyAsync(novel.Id, CancellationToken.None);

        // Assert
        using var memoryStream = new MemoryStream(zipBytes);
        using var archive = new ZipArchive(memoryStream, ZipArchiveMode.Read);
        var scriptEntry = archive.GetEntry("game/script.rpy");
        
        using var scriptStream = scriptEntry!.Open();
        using var reader = new StreamReader(scriptStream, Encoding.UTF8);
        var scriptContent = await reader.ReadToEndAsync();

        Assert.Contains("Тестовая Новелла", scriptContent);
        Assert.Contains("Алиса", scriptContent);
        Assert.Contains("Привет, мир!", scriptContent);
    }

    [Fact]
    public async Task ExportToRenPyAsync_ZipContainsGameDirectory()
    {
        // Arrange
        var novel = Novel.Create("Test", "start");
        var character = Character.Create("Test", Color.FromHex("#ffffff"), null);
        novel.AddCharacter(character);

        _mockRepository
            .Setup(x => x.GetByIdAsync(novel.Id, It.IsAny<CancellationToken>()))
            .ReturnsAsync(novel);

        // Act
        var zipBytes = await _exporter.ExportToRenPyAsync(novel.Id, CancellationToken.None);

        // Assert
        using var memoryStream = new MemoryStream(zipBytes);
        using var archive = new ZipArchive(memoryStream, ZipArchiveMode.Read);

        var gameEntries = archive.Entries.Where(e => e.FullName.StartsWith("game/")).ToList();
        Assert.NotEmpty(gameEntries);
        Assert.Contains(gameEntries, e => e.FullName == "game/script.rpy");
    }

    [Fact]
    public async Task ExportToRenPyAsync_CallsRepositoryOnce()
    {
        // Arrange
        var novel = Novel.Create("Test", "start");
        var character = Character.Create("Test", Color.FromHex("#ffffff"), null);
        novel.AddCharacter(character);

        _mockRepository
            .Setup(x => x.GetByIdAsync(novel.Id, It.IsAny<CancellationToken>()))
            .ReturnsAsync(novel);

        // Act
        await _exporter.ExportToRenPyAsync(novel.Id, CancellationToken.None);

        // Assert
        _mockRepository.Verify(
            x => x.GetByIdAsync(novel.Id, It.IsAny<CancellationToken>()),
            Times.Once
        );
    }
}
