using Moq;
using NoviVovi.Infrastructure.Exporters.RenPy.Core.Characters.Models;
using NoviVovi.Infrastructure.Exporters.RenPy.Core.Labels.Models;
using NoviVovi.Infrastructure.Exporters.RenPy.Core.Novels.Models;
using NoviVovi.Infrastructure.Exporters.RenPy.Core.Scene.Models;
using NoviVovi.Infrastructure.Exporters.RenPy.Core.Statements.Models;
using NoviVovi.Infrastructure.Exporters.RenPy.Services.Resources;
using NoviVovi.Infrastructure.Exporters.RenPy.Services.Script;

namespace NoviVovi.Infrastructure.Tests.Exporters.RenPy.Services.Script;

public class RenPyScriptGeneratorTests
{
    private readonly Mock<IEmbeddedResourceLoader> _mockResourceLoader;
    private readonly IRenPyStatementRenderer _statementRenderer;
    private readonly RenPyScriptGenerator _generator;

    public RenPyScriptGeneratorTests()
    {
        _mockResourceLoader = new Mock<IEmbeddedResourceLoader>();
        _statementRenderer = new RenPyStatementRenderer();
        _generator = new RenPyScriptGenerator(_mockResourceLoader.Object, _statementRenderer);
    }

    // Helper method to create default transform for backgrounds
    private static RenPyTransform DefaultBackgroundTransform() => 
        new(XPos: 0, YPos: 0, Zoom: 1.0, XZoom: 1.0, YZoom: 1.0, Rotate: 0.0, ZOrder: 0);

    [Fact]
    public async Task GenerateAsync_SimpleNovel_GeneratesValidScript()
    {
        // Arrange
        var template = """
## Generated by NoviVovi - {{ title }}
## https://github.com/yourusername/novivovi

## Character Definitions
{{~ for character in characters ~}}
define {{ character.variable_name }} = Character("{{ character.display_name }}", color="{{ character.color }}")
{{~ end ~}}

## Game Start
label start:
{{~ for label in labels ~}}
{{~ if label.identifier == start_label_id ~}}
{{~ for statement in label.statements ~}}
{{ render_statement statement }}
{{~ end ~}}
{{~ end ~}}
{{~ end ~}}
    return

## Labels
{{~ for label in labels ~}}
{{~ if label.identifier != start_label_id ~}}

label {{ label.identifier }}:
{{~ for statement in label.statements ~}}
{{ render_statement statement }}
{{~ end ~}}
    return
{{~ end ~}}
{{~ end ~}}
""";

        _mockResourceLoader
            .Setup(x => x.LoadTextResourceAsync(It.IsAny<string>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(template);

        var novel = new RenPyNovel
        {
            Title = "Test Novel",
            StartLabelId = "label_start",
            Characters = new List<RenPyCharacter>
            {
                new() { VariableName = "char_alice", DisplayName = "Alice", Color = "#FF5733" }
            },
            Labels = new List<RenPyLabel>
            {
                new()
                {
                    Identifier = "label_start",
                    Statements = new List<RenPyStatement>
                    {
                        new RenPySceneStatement("bg_room", DefaultBackgroundTransform()),
                        new RenPyReplicaStatement("char_alice", "Hello!")
                    }
                }
            }
        };

        // Act
        var result = await _generator.GenerateAsync(novel);

        // Assert
        Assert.Contains("## Generated by NoviVovi - Test Novel", result);
        Assert.Contains("define char_alice = Character(\"Alice\", color=\"#FF5733\")", result);
        Assert.Contains("label start:", result);
        Assert.Contains("return", result);
    }

    [Fact]
    public async Task GenerateAsync_MultipleCharacters_GeneratesAllCharacterDefinitions()
    {
        // Arrange
        var template = """
## Character Definitions
{{~ for character in characters ~}}
define {{ character.variable_name }} = Character("{{ character.display_name }}", color="{{ character.color }}")
{{~ end ~}}

label start:
    return
""";

        _mockResourceLoader
            .Setup(x => x.LoadTextResourceAsync(It.IsAny<string>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(template);

        var novel = new RenPyNovel
        {
            Title = "Multi Character Novel",
            StartLabelId = "label_start",
            Characters = new List<RenPyCharacter>
            {
                new() { VariableName = "char_alice", DisplayName = "Alice", Color = "#FF5733" },
                new() { VariableName = "char_bob", DisplayName = "Bob", Color = "#33FF57" },
                new() { VariableName = "char_charlie", DisplayName = "Charlie", Color = "#3357FF" }
            },
            Labels = new List<RenPyLabel>
            {
                new() { Identifier = "label_start", Statements = new List<RenPyStatement>() }
            }
        };

        // Act
        var result = await _generator.GenerateAsync(novel);

        // Assert
        Assert.Contains("define char_alice = Character(\"Alice\", color=\"#FF5733\")", result);
        Assert.Contains("define char_bob = Character(\"Bob\", color=\"#33FF57\")", result);
        Assert.Contains("define char_charlie = Character(\"Charlie\", color=\"#3357FF\")", result);
    }

    [Fact]
    public async Task GenerateAsync_MultipleLabels_GeneratesStartAndOtherLabels()
    {
        // Arrange
        var template = """
label start:
{{~ for label in labels ~}}
{{~ if label.identifier == start_label_id ~}}
{{~ for statement in label.statements ~}}
{{ render_statement statement }}
{{~ end ~}}
{{~ end ~}}
{{~ end ~}}
    return

## Labels
{{~ for label in labels ~}}
{{~ if label.identifier != start_label_id ~}}

label {{ label.identifier }}:
{{~ for statement in label.statements ~}}
{{ render_statement statement }}
{{~ end ~}}
    return
{{~ end ~}}
{{~ end ~}}
""";

        _mockResourceLoader
            .Setup(x => x.LoadTextResourceAsync(It.IsAny<string>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(template);

        var novel = new RenPyNovel
        {
            Title = "Multi Label Novel",
            StartLabelId = "label_start",
            Characters = new List<RenPyCharacter>(),
            Labels = new List<RenPyLabel>
            {
                new()
                {
                    Identifier = "label_start",
                    Statements = new List<RenPyStatement>
                    {
                        new RenPyJumpStatement("label_chapter1")
                    }
                },
                new()
                {
                    Identifier = "label_chapter1",
                    Statements = new List<RenPyStatement>
                    {
                        new RenPySceneStatement("bg_chapter1", DefaultBackgroundTransform())
                    }
                },
                new()
                {
                    Identifier = "label_chapter2",
                    Statements = new List<RenPyStatement>
                    {
                        new RenPySceneStatement("bg_chapter2", DefaultBackgroundTransform())
                    }
                }
            }
        };

        // Act
        var result = await _generator.GenerateAsync(novel);

        // Assert
        Assert.Contains("label start:", result);
        Assert.Contains("label label_chapter1:", result);
        Assert.Contains("label label_chapter2:", result);
    }

    [Fact]
    public async Task GenerateAsync_EmptyNovel_GeneratesMinimalScript()
    {
        // Arrange
        var template = """
## Generated by NoviVovi - {{ title }}

label start:
    return
""";

        _mockResourceLoader
            .Setup(x => x.LoadTextResourceAsync(It.IsAny<string>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(template);

        var novel = new RenPyNovel
        {
            Title = "Empty Novel",
            StartLabelId = "label_start",
            Characters = new List<RenPyCharacter>(),
            Labels = new List<RenPyLabel>
            {
                new() { Identifier = "label_start", Statements = new List<RenPyStatement>() }
            }
        };

        // Act
        var result = await _generator.GenerateAsync(novel);

        // Assert
        Assert.Contains("## Generated by NoviVovi - Empty Novel", result);
        Assert.Contains("label start:", result);
        Assert.Contains("return", result);
    }

    [Fact]
    public async Task GenerateAsync_CyrillicCharacters_GeneratesCorrectEncoding()
    {
        // Arrange
        var template = """
## Character Definitions
{{~ for character in characters ~}}
define {{ character.variable_name }} = Character("{{ character.display_name }}", color="{{ character.color }}")
{{~ end ~}}

label start:
    return
""";

        _mockResourceLoader
            .Setup(x => x.LoadTextResourceAsync(It.IsAny<string>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(template);

        var novel = new RenPyNovel
        {
            Title = "Русский роман",
            StartLabelId = "label_start",
            Characters = new List<RenPyCharacter>
            {
                new() { VariableName = "char_natasha", DisplayName = "Наташа", Color = "#FF5733" },
                new() { VariableName = "char_ivan", DisplayName = "Иван", Color = "#33FF57" }
            },
            Labels = new List<RenPyLabel>
            {
                new() { Identifier = "label_start", Statements = new List<RenPyStatement>() }
            }
        };

        // Act
        var result = await _generator.GenerateAsync(novel);

        // Assert
        Assert.Contains("define char_natasha = Character(\"Наташа\", color=\"#FF5733\")", result);
        Assert.Contains("define char_ivan = Character(\"Иван\", color=\"#33FF57\")", result);
    }

    [Fact]
    public async Task GenerateAsync_ComplexNovel_GeneratesCompleteScript()
    {
        // Arrange
        var template = """
## Generated by NoviVovi - {{ title }}

## Character Definitions
{{~ for character in characters ~}}
define {{ character.variable_name }} = Character("{{ character.display_name }}", color="{{ character.color }}")
{{~ end ~}}

## Game Start
label start:
{{~ for label in labels ~}}
{{~ if label.identifier == start_label_id ~}}
{{~ for statement in label.statements ~}}
{{ render_statement statement }}
{{~ end ~}}
{{~ end ~}}
{{~ end ~}}
    return

## Labels
{{~ for label in labels ~}}
{{~ if label.identifier != start_label_id ~}}

label {{ label.identifier }}:
{{~ for statement in label.statements ~}}
{{ render_statement statement }}
{{~ end ~}}
    return
{{~ end ~}}
{{~ end ~}}
""";

        _mockResourceLoader
            .Setup(x => x.LoadTextResourceAsync(It.IsAny<string>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(template);

        var novel = new RenPyNovel
        {
            Title = "Complex Novel",
            StartLabelId = "label_start",
            Characters = new List<RenPyCharacter>
            {
                new() { VariableName = "char_alice", DisplayName = "Alice", Color = "#FF5733" }
            },
            Labels = new List<RenPyLabel>
            {
                new()
                {
                    Identifier = "label_start",
                    Statements = new List<RenPyStatement>
                    {
                        new RenPySceneStatement("bg_room", DefaultBackgroundTransform()),
                        new RenPyShowCharacterStatement("alice", "happy", new RenPyTransform(640, 0, 1.0, 1.0, 1.0, 0.0, 0)),
                        new RenPyReplicaStatement("char_alice", "Hello, world!"),
                        new RenPyJumpStatement("label_end")
                    }
                },
                new()
                {
                    Identifier = "label_end",
                    Statements = new List<RenPyStatement>()
                }
            }
        };

        // Act
        var result = await _generator.GenerateAsync(novel);

        // Assert
        Assert.Contains("## Generated by NoviVovi - Complex Novel", result);
        Assert.Contains("define char_alice = Character(\"Alice\", color=\"#FF5733\")", result);
        Assert.Contains("label start:", result);
        Assert.Contains("label label_end:", result);
        Assert.Contains("scene bg_room:", result);
        Assert.Contains("show alice happy:", result);
        Assert.Contains("char_alice \"Hello, world!\"", result);
        Assert.Contains("jump label_end", result);
    }

    [Fact]
    public async Task GenerateAsync_LoadsCorrectTemplateResource()
    {
        // Arrange
        var template = "label start:\n    return";
        
        _mockResourceLoader
            .Setup(x => x.LoadTextResourceAsync(
                "NoviVovi.Infrastructure.Exporters.RenPy.Templates.script.rpy.sbn",
                It.IsAny<CancellationToken>()))
            .ReturnsAsync(template);

        var novel = new RenPyNovel
        {
            Title = "Test",
            StartLabelId = "label_start",
            Characters = new List<RenPyCharacter>(),
            Labels = new List<RenPyLabel>
            {
                new() { Identifier = "label_start", Statements = new List<RenPyStatement>() }
            }
        };

        // Act
        await _generator.GenerateAsync(novel);

        // Assert
        _mockResourceLoader.Verify(
            x => x.LoadTextResourceAsync(
                "NoviVovi.Infrastructure.Exporters.RenPy.Templates.script.rpy.sbn",
                It.IsAny<CancellationToken>()),
            Times.Once);
    }

    [Fact]
    public async Task GenerateAsync_PassesCancellationToken()
    {
        // Arrange
        var template = "label start:\n    return";
        var cts = new CancellationTokenSource();
        
        _mockResourceLoader
            .Setup(x => x.LoadTextResourceAsync(It.IsAny<string>(), cts.Token))
            .ReturnsAsync(template);

        var novel = new RenPyNovel
        {
            Title = "Test",
            StartLabelId = "label_start",
            Characters = new List<RenPyCharacter>(),
            Labels = new List<RenPyLabel>
            {
                new() { Identifier = "label_start", Statements = new List<RenPyStatement>() }
            }
        };

        // Act
        await _generator.GenerateAsync(novel, cts.Token);

        // Assert
        _mockResourceLoader.Verify(
            x => x.LoadTextResourceAsync(It.IsAny<string>(), cts.Token),
            Times.Once);
    }

    [Fact]
    public async Task GenerateAsync_NoCharacters_GeneratesScriptWithoutCharacterDefinitions()
    {
        // Arrange
        var template = """
## Character Definitions
{{~ for character in characters ~}}
define {{ character.variable_name }} = Character("{{ character.display_name }}", color="{{ character.color }}")
{{~ end ~}}

label start:
    return
""";

        _mockResourceLoader
            .Setup(x => x.LoadTextResourceAsync(It.IsAny<string>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(template);

        var novel = new RenPyNovel
        {
            Title = "No Characters Novel",
            StartLabelId = "label_start",
            Characters = new List<RenPyCharacter>(),
            Labels = new List<RenPyLabel>
            {
                new() { Identifier = "label_start", Statements = new List<RenPyStatement>() }
            }
        };

        // Act
        var result = await _generator.GenerateAsync(novel);

        // Assert
        Assert.Contains("## Character Definitions", result);
        Assert.DoesNotContain("define char_", result);
        Assert.Contains("label start:", result);
    }

    [Fact]
    public async Task GenerateAsync_SpecialCharactersInTitle_EscapesCorrectly()
    {
        // Arrange
        var template = "## Generated by NoviVovi - {{ title }}\n\nlabel start:\n    return";

        _mockResourceLoader
            .Setup(x => x.LoadTextResourceAsync(It.IsAny<string>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(template);

        var novel = new RenPyNovel
        {
            Title = "Test \"Novel\" with 'Quotes'",
            StartLabelId = "label_start",
            Characters = new List<RenPyCharacter>(),
            Labels = new List<RenPyLabel>
            {
                new() { Identifier = "label_start", Statements = new List<RenPyStatement>() }
            }
        };

        // Act
        var result = await _generator.GenerateAsync(novel);

        // Assert
        Assert.Contains("Test \"Novel\" with 'Quotes'", result);
    }
}


