using NoviVovi.Infrastructure.Exporters.RenPy.Services.Resources;
using Xunit;

namespace NoviVovi.Infrastructure.Tests.Exporters.RenPy.Services.Resources;

/// <summary>
/// Tests for EmbeddedResourceLoader.
/// </summary>
public class EmbeddedResourceLoaderTests
{
    private readonly EmbeddedResourceLoader _loader;

    public EmbeddedResourceLoaderTests()
    {
        _loader = new EmbeddedResourceLoader();
    }

    [Fact]
    public async Task LoadTextResourceAsync_ValidResource_ReturnsContent()
    {
        // Arrange
        var resourceName = "NoviVovi.Infrastructure.Exporters.RenPy.Templates.script.rpy.sbn";

        // Act
        var result = await _loader.LoadTextResourceAsync(resourceName);

        // Assert
        Assert.NotNull(result);
        Assert.NotEmpty(result);
        Assert.Contains("Generated by NoviVovi", result);
    }

    [Fact]
    public async Task LoadTextResourceAsync_NonExistentResource_ThrowsException()
    {
        // Arrange
        var resourceName = "NonExistent.Resource.txt";

        // Act & Assert
        await Assert.ThrowsAsync<InvalidOperationException>(
            () => _loader.LoadTextResourceAsync(resourceName)
        );
    }

    [Fact]
    public async Task LoadStreamResourceAsync_ValidResource_ReturnsStream()
    {
        // Arrange
        var resourceName = "NoviVovi.Infrastructure.Exporters.RenPy.Templates.script.rpy.sbn";

        // Act
        var stream = await _loader.LoadStreamResourceAsync(resourceName);

        // Assert
        Assert.NotNull(stream);
        Assert.True(stream.CanRead);
        stream.Dispose();
    }

    [Fact]
    public async Task LoadStreamResourceAsync_NonExistentResource_ReturnsNull()
    {
        // Arrange
        var resourceName = "NonExistent.Resource.txt";

        // Act
        var stream = await _loader.LoadStreamResourceAsync(resourceName);

        // Assert
        Assert.Null(stream);
    }

    [Fact]
    public async Task LoadTextResourceAsync_CancellationToken_PropagatesCorrectly()
    {
        // Arrange
        var resourceName = "NoviVovi.Infrastructure.Exporters.RenPy.Templates.script.rpy.sbn";
        var cts = new CancellationTokenSource();

        // Act
        var result = await _loader.LoadTextResourceAsync(resourceName, cts.Token);

        // Assert
        Assert.NotNull(result);
    }

    [Fact]
    public async Task LoadTextResourceAsync_BaseProjectZip_CanLoadBinaryResource()
    {
        // Arrange
        var resourceName = "NoviVovi.Infrastructure.Exporters.RenPy.Resources.BaseProject.zip";

        // Act
        var stream = await _loader.LoadStreamResourceAsync(resourceName);

        // Assert
        if (stream != null)
        {
            Assert.True(stream.Length > 0);
            stream.Dispose();
        }
        // If null, BaseProject.zip is optional, so test passes
    }

    [Fact]
    public async Task LoadTextResourceAsync_TemplateContent_ContainsExpectedStructure()
    {
        // Arrange
        var resourceName = "NoviVovi.Infrastructure.Exporters.RenPy.Templates.script.rpy.sbn";

        // Act
        var result = await _loader.LoadTextResourceAsync(resourceName);

        // Assert
        Assert.Contains("Character Definitions", result);
        Assert.Contains("label start:", result);
        Assert.Contains("{{", result); // Scriban syntax
    }
}
